# Generated by Django 2.0.5 on 2018-06-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180531_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_linkedin',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_twitter',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
