# Generated by Django 2.0.5 on 2018-05-27 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20180525_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_by_company',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, related_name='comp', related_query_name='comps', to='company.Company'),
        ),
    ]
