# Generated by Django 2.0.5 on 2018-06-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20180527_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
